# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Surveillance.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.import os
import sys
import os

from nodemodels.cfnnodemodel import CfnNodeModel
from utils.StreamPlayer import StreamerPlayer

# 获取当前文件的父目录路径（即a文件夹的路径）
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)

# 将父目录添加到系统路径中
sys.path.append(parent_dir)
import socket
import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, Qt, pyqtSlot
from PyQt5.QtWidgets import QGroupBox, QWidget, QInputDialog, QLabel, QApplication
from utils.vlcPlayer import VideoPlayer

'''忽略import报错'''


class Surveillance(QWidget):
    def __init__(self, manager: CfnNodeModel):
        super().__init__()
        self.layout = QtWidgets.QHBoxLayout(self)
        self.setWindowTitle("Surveillance")
        self.setGeometry(0, 0, 1920, 1080)
        self.groupBox = QGroupBox("")
        self.node_manager = manager
        self._init_signals()
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "border: none;\n"
                                    "border-radius: 3px;\n"
                                    "background-color: #001135;")

        font = QtGui.QFont()
        font.setFamily("微软雅黑")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")

        self.top_box = QtWidgets.QGroupBox(self.groupBox)
        self.top_box.setTitle("")
        self.top_box.setObjectName("top_box")
        self.top_box.setStyleSheet("QGroupBox { border: 2px solid #2F528F; border-radius: 20px; }")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_box)
        self.horizontalLayout.setObjectName("horizontalLayout")

        current_datetime = datetime.datetime.now()
        formatted_datetime = current_datetime.strftime("%Y-%m-%d %H:%M:%S")

        font.setBold(True)
        font.setPointSize(10)

        self.label = QtWidgets.QLabel(self.top_box)
        self.label.setObjectName("label")
        self.label.setFont(font)
        self.label.setText(str(formatted_datetime))
        self.horizontalLayout.addWidget(self.label)

        spacerItem1 = QtWidgets.QSpacerItem(176, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.verticalLayout.addWidget(self.top_box)

        self.player_frame = QtWidgets.QFrame(self.groupBox)
        self.player_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.player_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.player_frame.setObjectName("player_frame")
        self.verticalLayout.addWidget(self.player_frame)

        self.horizontalLayout_v = QtWidgets.QHBoxLayout(self.player_frame)

        target_ip = self.node_manager.demo_conf.get_node('client')['node_ip']
        target_port = self.node_manager.demo_conf.get_node('client')['port']

        self.vlc_streamer = StreamerPlayer(parent=None, addr=target_ip, port=target_port, local_port="2234",
                                           video_source="dshow://:dshow-vdev='Integrated Camera'")

        hostname = socket.gethostname()
        ip_address = socket.gethostbyname(hostname)
        self.vlc_player = VideoPlayer(frame=self.player_frame, videoPath="udp://@" + ip_address + ":2234")
        # self.vlc_player.startPlayer()
        self.horizontalLayout_v.addWidget(self.vlc_player)

        self.bottom_box = QtWidgets.QGroupBox(self.groupBox)
        self.bottom_box.setTitle("")
        self.bottom_box.setObjectName("bottom_box")
        self.bottom_box.setStyleSheet("border: none;")
        # self.bottom_box.setStyleSheet("QGroupBox { border: 2px solid #2F528F; border-radius: 20px; }")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.volume = QtWidgets.QLabel(self.bottom_box)
        self.volume.setObjectName("volume")
        self.volume.setText("Volume")
        self.volume.setFont(font)
        self.volume.setStyleSheet("border: none;")
        self.horizontalLayout_2.addWidget(self.volume)

        self.volumeSlider = QtWidgets.QSlider(self.bottom_box)
        self.volumeSlider.setMaximumSize(QtCore.QSize(200, 30))
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.volumeSlider.setMinimum(0)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setMinimumWidth(50)
        self.volumeSlider.setStyleSheet("border: none;")
        self.volumeSlider.setValue(100)
        self.volumeSlider.valueChanged.connect(self.update_volume)
        self.horizontalLayout_2.addWidget(self.volumeSlider)

        self.volumenum = QtWidgets.QLabel(self.bottom_box)
        self.volumenum.setObjectName("volumenum")
        self.volumenum.setText("100%")
        self.volumenum.setFont(font)
        self.volumenum.setFixedWidth(60)
        self.volumenum.setStyleSheet("border: none;")
        self.horizontalLayout_2.addWidget(self.volumenum)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)

        font.setBold(True)
        font.setPointSize(15)
        self.start_end_btn = QtWidgets.QPushButton(self.bottom_box)
        self.start_end_btn.setObjectName("start_end_btn")
        self.start_end_btn.setStyleSheet(
            "QPushButton { background-color: #4CAF50; color: white; border: 0px solid; border-radius: 10px;}"
            "QPushButton:hover { background-color: #45a049; }")
        self.start_end_btn.clicked.connect(self.start_event)
        self.start_end_btn.setText("Start")
        self.start_end_btn.setFixedWidth(200)
        self.start_end_btn.setFixedHeight(70)
        self.start_end_btn.setFont(font)
        self.horizontalLayout_2.addWidget(self.start_end_btn)
        self.start_end_btn.setVisible(False)

        self.verticalLayout.addWidget(self.bottom_box)

        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 1)

        self.layout.addWidget(self.groupBox)
        self.layout.setContentsMargins(0, 0, 0, 0)

        self.timer_timeupdate = QTimer(self)
        self.timer_timeupdate.timeout.connect(self.update_time)
        self.timer_timeupdate.start(1000)

    def _init_signals(self):
        self.node_manager.signal_emitter.QtSignals.service_ctrl.connect(self.slave_service_ctrl)

    @pyqtSlot(str, str, str)
    def slave_service_ctrl(self, service_name: str, action: str, params: str):
        print(f"slave_service_ctrl >>> ... {service_name},{action},{params}")
        service_args = params.split('#')
        # addr, port, interface = service_args[0], service_args[1], service_args[2]
        if action == 'up':
            self.vlc_streamer.startStream()
            self.vlc_player.startPlayer()
        elif action == 'down':
            while True:
                if self.vlc_streamer.video_streamer.is_playing() or self.vlc_player.media_player.is_playing():
                    self.vlc_streamer.video_streamer.pause()
                    self.vlc_player.media_player.pause()
                else:
                    break

    def update_time(self):
        current_datetime = datetime.datetime.now()
        formatted_datetime = current_datetime.strftime("%Y-%m-%d %H:%M:%S")
        self.label.setText(str(formatted_datetime))

    def update_volume(self, value):
        self.volumenum.setText(f"{value}%")
        self.vlc_player.media_player.audio_set_volume(value)

    def start_event(self):
        self.start_end_btn.setDisabled(True)

        if self.vlc_player.isHidden():
            self.vlc_player.show()
        else:
            self.vlc_player.hide()

        if not self.vlc_streamer.video_streamer.is_playing():  # not playing --> playing
            self.send_msg("Surveillance", "CPU: 0.672 Gflops", "MEM: 36.7 MB", "BW: 1.8 Mbps")
            self.vlc_streamer.startStream()
            self.vlc_player.startPlayer()
            self.start_end_btn.setText("Stop")
            self.start_end_btn.setStyleSheet(
                "QPushButton { background-color: #A60000; color: white; border: 0px solid; border-radius: 10px;}"
                "QPushButton:hover { background-color: #8F1613; }")
            self.start_end_btn.setDisabled(False)
        else:  # playing --> not playing
            self.vlc_streamer.stopStream()
            self.start_end_btn.setText("Start")
            self.start_end_btn.setStyleSheet(
                "QPushButton { background-color: #4CAF50; color: white; border: 0px solid; border-radius: 10px;}"
                "QPushButton:hover { background-color: #45a049; }")
            self.start_end_btn.setDisabled(False)
        self.start_end_btn.setVisible(False)

    def keyPressEvent(self, event):
        if event.key() == Qt.Key_S:
            self.send_msg("Surveillance", "CPU: 0.672 Gflops", "MEM: 36.7 MB", "BW: 1.8 Mbps")
        if event.key() == Qt.Key_C:
            self.send_msg("Crowded", "", "", "")
        if event.key() == Qt.Key_X:
            self.send_msg("UnCrowded", "", "", "")

    def send_msg(self, serviceName, cpu_val, mem_val, bw_val):
        udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        ip = '192.168.66.30'
        port = 10068
        if serviceName == "Crowded" or serviceName == "UnCrowded":
            message = serviceName
        else:
            message = "tag_" + str(serviceName) + "_" + str(cpu_val) + "_" + str(mem_val) + "_" + str(bw_val)
        try:
            # 发送消息
            udp_socket.sendto(message.encode(), (ip, port))
            print(f"Sent message: {message} to {ip}:{port}")
        except Exception as e:
            print(f"Error while sending message: {e}")
        finally:
            # 关闭套接字
            udp_socket.close()

    def shut_down(self):
        self.vlc_player.stopPlayer()
        self.vlc_streamer.stopStream()

    def closeEvent(self, event):
        self.shut_down()
        event.accept()
