# -*- coding: utf-8 -*-
"""
@Time: 5/17/2024 11:44 AM
@Author: Honggang Yuan
@Email: honggang.yuan@nokia-sbell.com
Description: 
"""
from copy import deepcopy

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QGroupBox, QVBoxLayout, QPushButton

from PyQt5.QtGui import QColor
from PyQt5.QtCore import QTimer
from random import randint

from resourcevisiualize.speedmeter import SpeedMeter

"""
部件已添加注释，共3个窗口展示3个node信息
其内部组成完全一致，使用下标区分，如master,worker1,label_3,processbar_2
node2，3的部件注释可以通过更改下标的方式查看node1的对应部件注释
"""


class Ui_window(object):
    def setupUi(self, window):
        """
        包含所有的窗口
        """
        window.setObjectName("window")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(window.sizePolicy().hasHeightForWidth())
        window.setSizePolicy(sizePolicy)
        window.setStyleSheet("background-color: #001135;")

        """
        包含3个node展示页面的主框架，布局为Horizontal，3个node水平展示
        """
        self.horizontalLayout = QtWidgets.QVBoxLayout(window)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.main_title = QtWidgets.QLabel("实施感知的算网资源")
        self.main_title_font = QtGui.QFont("Arial", 30, QtGui.QFont.Bold)
        self.main_title.setFont(self.main_title_font)
        self.main_title.setStyleSheet("color:rgb(146,208,80)")
        self.main_title.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignCenter)
        self.child_title = QtWidgets.QLabel("")
        self.child_title.setStyleSheet("color:rgb(0,17,53)")
        self.child_title.setFont(QtGui.QFont("Arial", 4, QtGui.QFont.Bold))
        self.main_title.setStyleSheet("color:rgb(146,208,80)")
        self.main_title_layout = QtWidgets.QVBoxLayout()
        self.main_title_layout.addWidget(self.child_title)
        self.main_title_layout.addWidget(self.main_title)
        self.main_title_layout.addWidget(self.child_title)
        self.horizontalLayout.addLayout(self.main_title_layout)

        self.status_monitor = QtWidgets.QHBoxLayout()
        self.status_monitor.setObjectName("status_monitor")

        """
        第一个node窗口，布局Vertical，包含5个部件
        窗口label、资源窗口、网络占用码表、Disk、File
        """
        self.node1 = QtWidgets.QGroupBox(window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.node1.sizePolicy().hasHeightForWidth())
        self.node1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.node1.setFont(font)
        self.node1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "border: 3px solid #2F528F;\n"
                                 "border-radius: 20px;")
        self.node1.setTitle("")
        self.node1.setObjectName("node1")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.node1)
        self.verticalLayout_1.setContentsMargins(-1, 8, -1, 4)
        self.verticalLayout_1.setObjectName("verticalLayout")

        # 选择展示node的下拉框

        # 第一个部件，展示node名称，之后切换时需要动态变动
        self.label_1 = QtWidgets.QLabel(self.node1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("border: none;")
        self.label_1.setObjectName("label")
        self.verticalLayout_1.addWidget(self.label_1)

        # 第二个部件，展示资源占用，包括CPU、内存、网络延迟
        self.resource_1 = QtWidgets.QGroupBox(self.node1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resource_1.sizePolicy().hasHeightForWidth())
        self.resource_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.resource_1.setFont(font)
        self.resource_1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "border: none;")
        self.resource_1.setTitle("")
        self.resource_1.setObjectName("resource_1")
        self.gridLayout = QtWidgets.QGridLayout(self.resource_1)
        self.gridLayout.setObjectName("gridLayout")

        # 显示CPU label文字
        self.cpu_1 = QtWidgets.QLabel(self.resource_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_1.sizePolicy().hasHeightForWidth())
        self.cpu_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.cpu_1.setFont(font)
        self.cpu_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpu_1.setObjectName("cpu_1")
        self.gridLayout.addWidget(self.cpu_1, 0, 0, 1, 1)

        # 动态进度条，用于显示CPU资源占用，颜色随占用程度改变
        self.cpu_bar_1 = QtWidgets.QProgressBar(self.resource_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_bar_1.sizePolicy().hasHeightForWidth())
        self.cpu_bar_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setKerning(True)
        self.cpu_bar_1.setFont(font)
        self.cpu_bar_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cpu_bar_1.setAutoFillBackground(False)
        self.cpu_bar_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpu_bar_1.setProperty("value", 24)

        self.cpu_bar_1.setTextVisible(False)
        self.cpu_bar_1.setFixedHeight(28)
        self.cpu_bar_1.setObjectName("cpu_bar_1")
        self.gridLayout.addWidget(self.cpu_bar_1, 0, 1, 1, 1)

        # 数字形式展示CPU占用度
        self.cpu_usage_1 = QtWidgets.QLabel(self.resource_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_usage_1.sizePolicy().hasHeightForWidth())
        self.cpu_usage_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.cpu_usage_1.setFont(font)
        self.cpu_usage_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpu_usage_1.setObjectName("cpu_usage_1")
        self.gridLayout.addWidget(self.cpu_usage_1, 0, 2, 1, 1)

        # 显示内存label文字
        self.mem_1 = QtWidgets.QLabel(self.resource_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mem_1.sizePolicy().hasHeightForWidth())
        self.mem_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.mem_1.setFont(font)
        self.mem_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem_1.setObjectName("mem_1")
        self.gridLayout.addWidget(self.mem_1, 1, 0, 1, 1)

        # 动态进度条，用于显示内存资源占用，颜色随占用程度改变
        self.mem_bar_1 = QtWidgets.QProgressBar(self.resource_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mem_bar_1.sizePolicy().hasHeightForWidth())
        self.mem_bar_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.mem_bar_1.setFont(font)
        self.mem_bar_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem_bar_1.setProperty("value", 24)
        self.mem_bar_1.setTextVisible(False)
        self.mem_bar_1.setFixedHeight(28)
        self.mem_bar_1.setObjectName("mem_bar_1")
        self.gridLayout.addWidget(self.mem_bar_1, 1, 1, 1, 1)

        # 数字形式展示内存占用度
        self.mem_usage_1 = QtWidgets.QLabel(self.resource_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mem_usage_1.sizePolicy().hasHeightForWidth())
        self.mem_usage_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.mem_usage_1.setFont(font)
        self.mem_usage_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem_usage_1.setObjectName("mem_usage_1")
        self.gridLayout.addWidget(self.mem_usage_1, 1, 2, 1, 1)

        # 显示延迟label文字
        self.delay_1 = QtWidgets.QLabel(self.resource_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_1.sizePolicy().hasHeightForWidth())
        self.delay_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.delay_1.setFont(font)
        self.delay_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.delay_1.setObjectName("delay_1")
        self.gridLayout.addWidget(self.delay_1, 2, 0, 1, 1)

        # 动态进度条，用于显示延迟，颜色动态改变
        self.delay_bar_1 = QtWidgets.QProgressBar(self.resource_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_bar_1.sizePolicy().hasHeightForWidth())
        self.delay_bar_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.delay_bar_1.setFont(font)
        self.delay_bar_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.delay_bar_1.setProperty("value", 24)
        self.delay_bar_1.setTextVisible(False)
        self.delay_bar_1.setFixedHeight(28)
        self.delay_bar_1.setObjectName("delay_bar_1")
        self.gridLayout.addWidget(self.delay_bar_1, 2, 1, 1, 1)

        # 数字形式展示延迟
        self.delay_num_1 = QtWidgets.QLabel(self.resource_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_num_1.sizePolicy().hasHeightForWidth())
        self.delay_num_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.delay_num_1.setFont(font)
        self.delay_num_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.delay_num_1.setObjectName("delay_4")
        self.gridLayout.addWidget(self.delay_num_1, 2, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 8)
        self.gridLayout.setColumnStretch(2, 2)
        self.verticalLayout_1.addWidget(self.resource_1)

        # 用于放置网络速度码表
        self.net_1 = QtWidgets.QGroupBox(self.node1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.net_1.sizePolicy().hasHeightForWidth())
        self.net_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.net_1.setFont(font)
        self.net_1.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.net_1.setObjectName("net_1")
        self.verticalLayout_1.addWidget(self.net_1)

        self.speed_meter_1 = SpeedMeter('', 'Gbps', 0, 100)
        self.layout_1 = QVBoxLayout()
        self.layout_1.addWidget(self.speed_meter_1)
        self.net_1.setLayout(self.layout_1)
        self.speed_meter_1.setGeometry(200, 200, 200, 200)

        # 用于展示I/O信息
        self.disk_1 = QtWidgets.QGroupBox(self.node1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disk_1.sizePolicy().hasHeightForWidth())
        self.disk_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.disk_1.setFont(font)
        self.disk_1.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.disk_1.setObjectName("disk_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.disk_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.read_label_1 = QtWidgets.QLabel(self.disk_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_label_1.sizePolicy().hasHeightForWidth())
        self.read_label_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.read_label_1.setFont(font)
        self.read_label_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.read_label_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.read_label_1.setObjectName("read_label_1")
        self.gridLayout_4.addWidget(self.read_label_1, 0, 1, 1, 1)
        self.write_label_1 = QtWidgets.QLabel(self.disk_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_label_1.sizePolicy().hasHeightForWidth())
        self.write_label_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.write_label_1.setFont(font)
        self.write_label_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.write_label_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.write_label_1.setObjectName("write_label_1")
        self.gridLayout_4.addWidget(self.write_label_1, 0, 2, 1, 1)
        self.sdal_1 = QtWidgets.QLabel(self.disk_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdal_1.sizePolicy().hasHeightForWidth())
        self.sdal_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sdal_1.setFont(font)
        self.sdal_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.sdal_1.setObjectName("sdal_1")
        self.gridLayout_4.addWidget(self.sdal_1, 1, 0, 1, 1)
        self.sdal_read_1 = QtWidgets.QLabel(self.disk_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdal_read_1.sizePolicy().hasHeightForWidth())
        self.sdal_read_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sdal_read_1.setFont(font)
        self.sdal_read_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.sdal_read_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sdal_read_1.setObjectName("sdal_read_1")
        self.gridLayout_4.addWidget(self.sdal_read_1, 1, 1, 1, 1)
        self.sdal_write_1 = QtWidgets.QLabel(self.disk_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdal_write_1.sizePolicy().hasHeightForWidth())
        self.sdal_write_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sdal_write_1.setFont(font)
        self.sdal_write_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.sdal_write_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sdal_write_1.setObjectName("sdal_write_1")
        self.gridLayout_4.addWidget(self.sdal_write_1, 1, 2, 1, 1)
        self.sr0_1 = QtWidgets.QLabel(self.disk_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr0_1.sizePolicy().hasHeightForWidth())
        self.sr0_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sr0_1.setFont(font)
        self.sr0_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.sr0_1.setObjectName("sr0_1")
        self.gridLayout_4.addWidget(self.sr0_1, 2, 0, 1, 1)
        self.sr0_read_1 = QtWidgets.QLabel(self.disk_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr0_read_1.sizePolicy().hasHeightForWidth())
        self.sr0_read_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sr0_read_1.setFont(font)
        self.sr0_read_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.sr0_read_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sr0_read_1.setObjectName("sr0_read_1")
        self.gridLayout_4.addWidget(self.sr0_read_1, 2, 1, 1, 1)
        self.sr0_write_1 = QtWidgets.QLabel(self.disk_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr0_write_1.sizePolicy().hasHeightForWidth())
        self.sr0_write_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sr0_write_1.setFont(font)
        self.sr0_write_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.sr0_write_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sr0_write_1.setObjectName("sr0_write_1")
        self.gridLayout_4.addWidget(self.sr0_write_1, 2, 2, 1, 1)
        self.verticalLayout_1.addWidget(self.disk_1)

        # 用于展示文件系统信息
        self.file_1 = QtWidgets.QGroupBox(self.node1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_1.sizePolicy().hasHeightForWidth())
        self.file_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.file_1.setFont(font)
        self.file_1.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.file_1.setObjectName("file_1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.file_1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.used_label_1 = QtWidgets.QLabel(self.file_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.used_label_1.sizePolicy().hasHeightForWidth())
        self.used_label_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.used_label_1.setFont(font)
        self.used_label_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.used_label_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.used_label_1.setObjectName("used_label_1")
        self.gridLayout_5.addWidget(self.used_label_1, 0, 1, 1, 1)
        self.total_label_1 = QtWidgets.QLabel(self.file_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_label_1.sizePolicy().hasHeightForWidth())
        self.total_label_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.total_label_1.setFont(font)
        self.total_label_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.total_label_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.total_label_1.setObjectName("total_label_1")
        self.gridLayout_5.addWidget(self.total_label_1, 0, 2, 1, 1)
        self.all_1 = QtWidgets.QLabel(self.file_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_1.sizePolicy().hasHeightForWidth())
        self.all_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.all_1.setFont(font)
        self.all_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.all_1.setObjectName("all_1")
        self.gridLayout_5.addWidget(self.all_1, 1, 0, 1, 1)
        self.all_used_1 = QtWidgets.QLabel(self.file_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_used_1.sizePolicy().hasHeightForWidth())
        self.all_used_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.all_used_1.setFont(font)
        self.all_used_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.all_used_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.all_used_1.setObjectName("all_used_1")
        self.gridLayout_5.addWidget(self.all_used_1, 1, 1, 1, 1)
        self.all_total_1 = QtWidgets.QLabel(self.file_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_total_1.sizePolicy().hasHeightForWidth())
        self.all_total_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.all_total_1.setFont(font)
        self.all_total_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.all_total_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.all_total_1.setObjectName("all_total_1")
        self.gridLayout_5.addWidget(self.all_total_1, 1, 2, 1, 1)
        self.boot_1 = QtWidgets.QLabel(self.file_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boot_1.sizePolicy().hasHeightForWidth())
        self.boot_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.boot_1.setFont(font)
        self.boot_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.boot_1.setObjectName("boot_1")
        self.gridLayout_5.addWidget(self.boot_1, 2, 0, 1, 1)
        self.boot_used_1 = QtWidgets.QLabel(self.file_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boot_used_1.sizePolicy().hasHeightForWidth())
        self.boot_used_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.boot_used_1.setFont(font)
        self.boot_used_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.boot_used_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.boot_used_1.setObjectName("boot_used_1")
        self.gridLayout_5.addWidget(self.boot_used_1, 2, 1, 1, 1)
        self.boot_total_1 = QtWidgets.QLabel(self.file_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boot_total_1.sizePolicy().hasHeightForWidth())
        self.boot_total_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.boot_total_1.setFont(font)
        self.boot_total_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.boot_total_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.boot_total_1.setObjectName("boot_total_1")
        self.gridLayout_5.addWidget(self.boot_total_1, 2, 2, 1, 1)
        self.verticalLayout_1.addWidget(self.file_1)
        self.verticalLayout_1.setStretch(1, 4)
        self.verticalLayout_1.setStretch(2, 8)
        self.verticalLayout_1.setStretch(3, 4)
        self.verticalLayout_1.setStretch(4, 4)
        self.status_monitor.addWidget(self.node1)

        """
        第二个node窗口，布局Vertical，包含5个部件
        窗口label、资源窗口、网络占用码表、Disk、File
        """
        self.node2 = QtWidgets.QGroupBox(window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.node2.sizePolicy().hasHeightForWidth())
        self.node2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.node2.setFont(font)
        self.node2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "border: 3px solid #2F528F;\n"
                                 "border-radius: 20px;")
        self.node2.setTitle("")
        self.node2.setObjectName("node2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.node2)
        self.verticalLayout_2.setContentsMargins(-1, 8, -1, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.label_2 = QtWidgets.QLabel(self.node2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.resource_2 = QtWidgets.QGroupBox(self.node2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resource_2.sizePolicy().hasHeightForWidth())
        self.resource_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.resource_2.setFont(font)
        self.resource_2.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.resource_2.setTitle("")
        self.resource_2.setObjectName("resource_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.resource_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cpu_2 = QtWidgets.QLabel(self.resource_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_2.sizePolicy().hasHeightForWidth())
        self.cpu_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.cpu_2.setFont(font)
        self.cpu_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpu_2.setObjectName("cpu_2")
        self.gridLayout_2.addWidget(self.cpu_2, 0, 0, 1, 1)
        self.cpu_bar_2 = QtWidgets.QProgressBar(self.resource_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_bar_2.sizePolicy().hasHeightForWidth())
        self.cpu_bar_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.cpu_bar_2.setFont(font)
        self.cpu_bar_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpu_bar_2.setProperty("value", 24)
        self.cpu_bar_2.setTextVisible(False)
        self.cpu_bar_2.setFixedHeight(28)
        self.cpu_bar_2.setObjectName("cpu_bar_2")
        self.gridLayout_2.addWidget(self.cpu_bar_2, 0, 1, 1, 1)
        self.cpu_usage_2 = QtWidgets.QLabel(self.resource_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_usage_2.sizePolicy().hasHeightForWidth())
        self.cpu_usage_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.cpu_usage_2.setFont(font)
        self.cpu_usage_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpu_usage_2.setObjectName("cpu_usage_2")
        self.gridLayout_2.addWidget(self.cpu_usage_2, 0, 2, 1, 1)
        self.mem_2 = QtWidgets.QLabel(self.resource_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mem_2.sizePolicy().hasHeightForWidth())
        self.mem_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.mem_2.setFont(font)
        self.mem_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem_2.setObjectName("mem_2")
        self.gridLayout_2.addWidget(self.mem_2, 1, 0, 1, 1)
        self.mem_bar_2 = QtWidgets.QProgressBar(self.resource_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mem_bar_2.sizePolicy().hasHeightForWidth())
        self.mem_bar_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.mem_bar_2.setFont(font)
        self.mem_bar_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem_bar_2.setProperty("value", 24)
        self.mem_bar_2.setTextVisible(False)
        self.mem_bar_2.setFixedHeight(28)
        self.mem_bar_2.setObjectName("mem_bar_2")
        self.gridLayout_2.addWidget(self.mem_bar_2, 1, 1, 1, 1)
        self.mem_usage_2 = QtWidgets.QLabel(self.resource_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mem_usage_2.sizePolicy().hasHeightForWidth())
        self.mem_usage_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.mem_usage_2.setFont(font)
        self.mem_usage_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem_usage_2.setObjectName("mem_usage_2")
        self.gridLayout_2.addWidget(self.mem_usage_2, 1, 2, 1, 1)
        self.delay_2 = QtWidgets.QLabel(self.resource_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_2.sizePolicy().hasHeightForWidth())
        self.delay_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.delay_2.setFont(font)
        self.delay_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.delay_2.setObjectName("delay_2")
        self.gridLayout_2.addWidget(self.delay_2, 2, 0, 1, 1)
        self.delay_bar_2 = QtWidgets.QProgressBar(self.resource_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_bar_2.sizePolicy().hasHeightForWidth())
        self.delay_bar_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.delay_bar_2.setFont(font)
        self.delay_bar_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.delay_bar_2.setProperty("value", 24)
        self.delay_bar_2.setTextVisible(False)
        self.delay_bar_2.setFixedHeight(28)
        self.delay_bar_2.setObjectName("delay_bar_2")
        self.gridLayout_2.addWidget(self.delay_bar_2, 2, 1, 1, 1)
        self.delay_num_2 = QtWidgets.QLabel(self.resource_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_num_2.sizePolicy().hasHeightForWidth())
        self.delay_num_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.delay_num_2.setFont(font)
        self.delay_num_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.delay_num_2.setObjectName("delay_num_2")
        self.gridLayout_2.addWidget(self.delay_num_2, 2, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 8)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.verticalLayout_2.addWidget(self.resource_2)
        self.net_2 = QtWidgets.QGroupBox(self.node2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.net_2.sizePolicy().hasHeightForWidth())
        self.net_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.net_2.setFont(font)
        self.net_2.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.net_2.setObjectName("net_2")

        self.speed_meter_2 = SpeedMeter('', 'Gbps', 0, 100)
        self.layout_2 = QVBoxLayout()
        self.layout_2.addWidget(self.speed_meter_2)
        self.net_2.setLayout(self.layout_2)
        self.speed_meter_2.setGeometry(200, 200, 200, 200)

        self.verticalLayout_2.addWidget(self.net_2)
        self.disk_2 = QtWidgets.QGroupBox(self.node2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disk_2.sizePolicy().hasHeightForWidth())
        self.disk_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.disk_2.setFont(font)
        self.disk_2.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.disk_2.setObjectName("disk_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.disk_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.read_label_2 = QtWidgets.QLabel(self.disk_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_label_2.sizePolicy().hasHeightForWidth())
        self.read_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.read_label_2.setFont(font)
        self.read_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.read_label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.read_label_2.setObjectName("read_label_2")
        self.gridLayout_6.addWidget(self.read_label_2, 0, 1, 1, 1)
        self.write_label_2 = QtWidgets.QLabel(self.disk_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_label_2.sizePolicy().hasHeightForWidth())
        self.write_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.write_label_2.setFont(font)
        self.write_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.write_label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.write_label_2.setObjectName("write_label_2")
        self.gridLayout_6.addWidget(self.write_label_2, 0, 2, 1, 1)
        self.sdal_2 = QtWidgets.QLabel(self.disk_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdal_2.sizePolicy().hasHeightForWidth())
        self.sdal_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sdal_2.setFont(font)
        self.sdal_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.sdal_2.setObjectName("sdal_2")
        self.gridLayout_6.addWidget(self.sdal_2, 1, 0, 1, 1)
        self.sdal_read_2 = QtWidgets.QLabel(self.disk_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdal_read_2.sizePolicy().hasHeightForWidth())
        self.sdal_read_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sdal_read_2.setFont(font)
        self.sdal_read_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.sdal_read_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sdal_read_2.setObjectName("sdal_read_2")
        self.gridLayout_6.addWidget(self.sdal_read_2, 1, 1, 1, 1)
        self.sdal_write_2 = QtWidgets.QLabel(self.disk_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdal_write_2.sizePolicy().hasHeightForWidth())
        self.sdal_write_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sdal_write_2.setFont(font)
        self.sdal_write_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.sdal_write_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sdal_write_2.setObjectName("sdal_write_2")
        self.gridLayout_6.addWidget(self.sdal_write_2, 1, 2, 1, 1)
        self.sr0_2 = QtWidgets.QLabel(self.disk_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr0_2.sizePolicy().hasHeightForWidth())
        self.sr0_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sr0_2.setFont(font)
        self.sr0_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.sr0_2.setObjectName("sr0_2")
        self.gridLayout_6.addWidget(self.sr0_2, 2, 0, 1, 1)
        self.sr0_read_2 = QtWidgets.QLabel(self.disk_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr0_read_2.sizePolicy().hasHeightForWidth())
        self.sr0_read_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sr0_read_2.setFont(font)
        self.sr0_read_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.sr0_read_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sr0_read_2.setObjectName("sr0_read_2")
        self.gridLayout_6.addWidget(self.sr0_read_2, 2, 1, 1, 1)
        self.sr0_write_2 = QtWidgets.QLabel(self.disk_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr0_write_2.sizePolicy().hasHeightForWidth())
        self.sr0_write_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sr0_write_2.setFont(font)
        self.sr0_write_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.sr0_write_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sr0_write_2.setObjectName("sr0_write_2")
        self.gridLayout_6.addWidget(self.sr0_write_2, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.disk_2)
        self.file_2 = QtWidgets.QGroupBox(self.node2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_2.sizePolicy().hasHeightForWidth())
        self.file_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.file_2.setFont(font)
        self.file_2.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.file_2.setObjectName("file_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.file_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.used_label_2 = QtWidgets.QLabel(self.file_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.used_label_2.sizePolicy().hasHeightForWidth())
        self.used_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.used_label_2.setFont(font)
        self.used_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.used_label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.used_label_2.setObjectName("used_label_2")
        self.gridLayout_7.addWidget(self.used_label_2, 0, 1, 1, 1)
        self.total_label_2 = QtWidgets.QLabel(self.file_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_label_2.sizePolicy().hasHeightForWidth())
        self.total_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.total_label_2.setFont(font)
        self.total_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.total_label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.total_label_2.setObjectName("total_label_2")
        self.gridLayout_7.addWidget(self.total_label_2, 0, 2, 1, 1)
        self.all_2 = QtWidgets.QLabel(self.file_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_2.sizePolicy().hasHeightForWidth())
        self.all_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.all_2.setFont(font)
        self.all_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.all_2.setObjectName("all_2")
        self.gridLayout_7.addWidget(self.all_2, 1, 0, 1, 1)
        self.all_used_2 = QtWidgets.QLabel(self.file_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_used_2.sizePolicy().hasHeightForWidth())
        self.all_used_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.all_used_2.setFont(font)
        self.all_used_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.all_used_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.all_used_2.setObjectName("all_used_2")
        self.gridLayout_7.addWidget(self.all_used_2, 1, 1, 1, 1)
        self.all_total_2 = QtWidgets.QLabel(self.file_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_total_2.sizePolicy().hasHeightForWidth())
        self.all_total_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.all_total_2.setFont(font)
        self.all_total_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.all_total_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.all_total_2.setObjectName("all_total_2")
        self.gridLayout_7.addWidget(self.all_total_2, 1, 2, 1, 1)
        self.boot_2 = QtWidgets.QLabel(self.file_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boot_2.sizePolicy().hasHeightForWidth())
        self.boot_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.boot_2.setFont(font)
        self.boot_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.boot_2.setObjectName("boot_2")
        self.gridLayout_7.addWidget(self.boot_2, 2, 0, 1, 1)
        self.boot_used_2 = QtWidgets.QLabel(self.file_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boot_used_2.sizePolicy().hasHeightForWidth())
        self.boot_used_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.boot_used_2.setFont(font)
        self.boot_used_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.boot_used_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.boot_used_2.setObjectName("boot_used_2")
        self.gridLayout_7.addWidget(self.boot_used_2, 2, 1, 1, 1)
        self.boot_total_2 = QtWidgets.QLabel(self.file_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boot_total_2.sizePolicy().hasHeightForWidth())
        self.boot_total_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.boot_total_2.setFont(font)
        self.boot_total_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.boot_total_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.boot_total_2.setObjectName("boot_total_2")
        self.gridLayout_7.addWidget(self.boot_total_2, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.file_2)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(2, 8)
        self.verticalLayout_2.setStretch(3, 4)
        self.verticalLayout_2.setStretch(4, 4)
        self.status_monitor.addWidget(self.node2)

        """
        第三个node窗口，布局Vertical，包含5个部件
        窗口label、资源窗口、网络占用码表、Disk、File
        """
        self.node3 = QtWidgets.QGroupBox(window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.node3.sizePolicy().hasHeightForWidth())
        self.node3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.node3.setFont(font)
        self.node3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "border: 3px solid #2F528F;\n"
                                 "border-radius: 20px;")
        self.node3.setTitle("")
        self.node3.setObjectName("node3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.node3)
        self.verticalLayout_3.setContentsMargins(-1, 8, -1, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.label_3 = QtWidgets.QLabel(self.node3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: none;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.resource_3 = QtWidgets.QGroupBox(self.node3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resource_3.sizePolicy().hasHeightForWidth())
        self.resource_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.resource_3.setFont(font)
        self.resource_3.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.resource_3.setTitle("")
        self.resource_3.setObjectName("resource_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.resource_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cpu_3 = QtWidgets.QLabel(self.resource_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_3.sizePolicy().hasHeightForWidth())
        self.cpu_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.cpu_3.setFont(font)
        self.cpu_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpu_3.setObjectName("cpu_3")
        self.gridLayout_3.addWidget(self.cpu_3, 0, 0, 1, 1)
        self.cpu_bar_3 = QtWidgets.QProgressBar(self.resource_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_bar_3.sizePolicy().hasHeightForWidth())
        self.cpu_bar_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.cpu_bar_3.setFont(font)
        self.cpu_bar_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpu_bar_3.setProperty("value", 24)
        self.cpu_bar_3.setTextVisible(False)
        self.cpu_bar_3.setFixedHeight(28)
        self.cpu_bar_3.setObjectName("cpu_bar_3")
        self.gridLayout_3.addWidget(self.cpu_bar_3, 0, 1, 1, 1)
        self.cpu_usage_3 = QtWidgets.QLabel(self.resource_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpu_usage_3.sizePolicy().hasHeightForWidth())
        self.cpu_usage_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.cpu_usage_3.setFont(font)
        self.cpu_usage_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.cpu_usage_3.setObjectName("cpu_usage_3")
        self.gridLayout_3.addWidget(self.cpu_usage_3, 0, 2, 1, 1)
        self.mem_3 = QtWidgets.QLabel(self.resource_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mem_3.sizePolicy().hasHeightForWidth())
        self.mem_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.mem_3.setFont(font)
        self.mem_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem_3.setObjectName("mem_3")
        self.gridLayout_3.addWidget(self.mem_3, 1, 0, 1, 1)
        self.mem_bar_3 = QtWidgets.QProgressBar(self.resource_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mem_bar_3.sizePolicy().hasHeightForWidth())
        self.mem_bar_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.mem_bar_3.setFont(font)
        self.mem_bar_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem_bar_3.setProperty("value", 24)
        self.mem_bar_3.setTextVisible(False)
        self.mem_bar_3.setFixedHeight(28)
        self.mem_bar_3.setObjectName("mem_bar_3")
        self.gridLayout_3.addWidget(self.mem_bar_3, 1, 1, 1, 1)
        self.mem_usage_3 = QtWidgets.QLabel(self.resource_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mem_usage_3.sizePolicy().hasHeightForWidth())
        self.mem_usage_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.mem_usage_3.setFont(font)
        self.mem_usage_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.mem_usage_3.setObjectName("mem_usage_3")
        self.gridLayout_3.addWidget(self.mem_usage_3, 1, 2, 1, 1)
        self.delay_3 = QtWidgets.QLabel(self.resource_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_3.sizePolicy().hasHeightForWidth())
        self.delay_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.delay_3.setFont(font)
        self.delay_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.delay_3.setObjectName("delay_3")
        self.gridLayout_3.addWidget(self.delay_3, 2, 0, 1, 1)
        self.delay_bar_3 = QtWidgets.QProgressBar(self.resource_3)
        self.delay_bar_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_bar_3.sizePolicy().hasHeightForWidth())
        self.delay_bar_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        self.delay_bar_3.setFont(font)
        self.delay_bar_3.setMouseTracking(False)
        self.delay_bar_3.setAutoFillBackground(False)
        self.delay_bar_3.setStyleSheet("")
        self.delay_bar_3.setProperty("value", 24)
        self.delay_bar_3.setTextVisible(False)
        self.delay_bar_3.setFixedHeight(28)
        self.delay_bar_3.setObjectName("delay_bar_3")
        self.gridLayout_3.addWidget(self.delay_bar_3, 2, 1, 1, 1)
        self.delay_num_3 = QtWidgets.QLabel(self.resource_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_num_3.sizePolicy().hasHeightForWidth())
        self.delay_num_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.delay_num_3.setFont(font)
        self.delay_num_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.delay_num_3.setObjectName("delay_num_3")
        self.gridLayout_3.addWidget(self.delay_num_3, 2, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 3)
        self.gridLayout_3.setColumnStretch(1, 8)
        self.gridLayout_3.setColumnStretch(2, 2)
        self.verticalLayout_3.addWidget(self.resource_3)
        self.net_3 = QtWidgets.QGroupBox(self.node3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.net_3.sizePolicy().hasHeightForWidth())
        self.net_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.net_3.setFont(font)
        self.net_3.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.net_3.setObjectName("net_3")

        self.speed_meter_3 = SpeedMeter('', 'Gbps', 0, 100)
        self.layout_3 = QVBoxLayout()
        self.layout_3.addWidget(self.speed_meter_3)
        self.net_3.setLayout(self.layout_3)
        self.speed_meter_3.setGeometry(200, 200, 200, 200)

        self.verticalLayout_3.addWidget(self.net_3)
        self.disk_3 = QtWidgets.QGroupBox(self.node3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disk_3.sizePolicy().hasHeightForWidth())
        self.disk_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.disk_3.setFont(font)
        self.disk_3.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.disk_3.setObjectName("disk_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.disk_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.read_label_3 = QtWidgets.QLabel(self.disk_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_label_3.sizePolicy().hasHeightForWidth())
        self.read_label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.read_label_3.setFont(font)
        self.read_label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.read_label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.read_label_3.setObjectName("read_label_3")
        self.gridLayout_8.addWidget(self.read_label_3, 0, 1, 1, 1)
        self.write_label_3 = QtWidgets.QLabel(self.disk_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_label_3.sizePolicy().hasHeightForWidth())
        self.write_label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.write_label_3.setFont(font)
        self.write_label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.write_label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.write_label_3.setObjectName("write_label_3")
        self.gridLayout_8.addWidget(self.write_label_3, 0, 2, 1, 1)
        self.sdal_3 = QtWidgets.QLabel(self.disk_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdal_3.sizePolicy().hasHeightForWidth())
        self.sdal_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sdal_3.setFont(font)
        self.sdal_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.sdal_3.setObjectName("sdal_3")
        self.gridLayout_8.addWidget(self.sdal_3, 1, 0, 1, 1)
        self.sdal_read_3 = QtWidgets.QLabel(self.disk_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdal_read_3.sizePolicy().hasHeightForWidth())
        self.sdal_read_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sdal_read_3.setFont(font)
        self.sdal_read_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.sdal_read_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sdal_read_3.setObjectName("sdal_read_3")
        self.gridLayout_8.addWidget(self.sdal_read_3, 1, 1, 1, 1)
        self.sdal_write_3 = QtWidgets.QLabel(self.disk_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sdal_write_3.sizePolicy().hasHeightForWidth())
        self.sdal_write_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sdal_write_3.setFont(font)
        self.sdal_write_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.sdal_write_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sdal_write_3.setObjectName("sdal_write_3")
        self.gridLayout_8.addWidget(self.sdal_write_3, 1, 2, 1, 1)
        self.sr0_3 = QtWidgets.QLabel(self.disk_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr0_3.sizePolicy().hasHeightForWidth())
        self.sr0_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sr0_3.setFont(font)
        self.sr0_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.sr0_3.setObjectName("sr0_3")
        self.gridLayout_8.addWidget(self.sr0_3, 2, 0, 1, 1)
        self.sr0_read_3 = QtWidgets.QLabel(self.disk_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr0_read_3.sizePolicy().hasHeightForWidth())
        self.sr0_read_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sr0_read_3.setFont(font)
        self.sr0_read_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.sr0_read_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sr0_read_3.setObjectName("sr0_read_3")
        self.gridLayout_8.addWidget(self.sr0_read_3, 2, 1, 1, 1)
        self.sr0_write_3 = QtWidgets.QLabel(self.disk_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sr0_write_3.sizePolicy().hasHeightForWidth())
        self.sr0_write_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.sr0_write_3.setFont(font)
        self.sr0_write_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.sr0_write_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.sr0_write_3.setObjectName("sr0_write_3")
        self.gridLayout_8.addWidget(self.sr0_write_3, 2, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.disk_3)
        self.file_3 = QtWidgets.QGroupBox(self.node3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_3.sizePolicy().hasHeightForWidth())
        self.file_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.file_3.setFont(font)
        self.file_3.setStyleSheet("color: rgb(255, 255, 255);border: none;")
        self.file_3.setObjectName("file_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.file_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.used_label_3 = QtWidgets.QLabel(self.file_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.used_label_3.sizePolicy().hasHeightForWidth())
        self.used_label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.used_label_3.setFont(font)
        self.used_label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.used_label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.used_label_3.setObjectName("used_label_3")
        self.gridLayout_9.addWidget(self.used_label_3, 0, 1, 1, 1)
        self.total_label_3 = QtWidgets.QLabel(self.file_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_label_3.sizePolicy().hasHeightForWidth())
        self.total_label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.total_label_3.setFont(font)
        self.total_label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.total_label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.total_label_3.setObjectName("total_label_3")
        self.gridLayout_9.addWidget(self.total_label_3, 0, 2, 1, 1)
        self.all_3 = QtWidgets.QLabel(self.file_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_3.sizePolicy().hasHeightForWidth())
        self.all_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.all_3.setFont(font)
        self.all_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.all_3.setObjectName("all_3")
        self.gridLayout_9.addWidget(self.all_3, 1, 0, 1, 1)
        self.all_used_3 = QtWidgets.QLabel(self.file_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_used_3.sizePolicy().hasHeightForWidth())
        self.all_used_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.all_used_3.setFont(font)
        self.all_used_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.all_used_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.all_used_3.setObjectName("all_used_3")
        self.gridLayout_9.addWidget(self.all_used_3, 1, 1, 1, 1)
        self.all_total_3 = QtWidgets.QLabel(self.file_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.all_total_3.sizePolicy().hasHeightForWidth())
        self.all_total_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.all_total_3.setFont(font)
        self.all_total_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.all_total_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.all_total_3.setObjectName("all_total_3")
        self.gridLayout_9.addWidget(self.all_total_3, 1, 2, 1, 1)
        self.boot_3 = QtWidgets.QLabel(self.file_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boot_3.sizePolicy().hasHeightForWidth())
        self.boot_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.boot_3.setFont(font)
        self.boot_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.boot_3.setObjectName("boot_3")
        self.gridLayout_9.addWidget(self.boot_3, 2, 0, 1, 1)
        self.boot_used_3 = QtWidgets.QLabel(self.file_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boot_used_3.sizePolicy().hasHeightForWidth())
        self.boot_used_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.boot_used_3.setFont(font)
        self.boot_used_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.boot_used_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.boot_used_3.setObjectName("boot_used_3")
        self.gridLayout_9.addWidget(self.boot_used_3, 2, 1, 1, 1)
        self.boot_total_3 = QtWidgets.QLabel(self.file_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boot_total_3.sizePolicy().hasHeightForWidth())
        self.boot_total_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.boot_total_3.setFont(font)
        self.boot_total_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.boot_total_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.boot_total_3.setObjectName("boot_total_3")
        self.gridLayout_9.addWidget(self.boot_total_3, 2, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.file_3)
        self.verticalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.setStretch(2, 8)
        self.verticalLayout_3.setStretch(3, 4)
        self.verticalLayout_3.setStretch(4, 4)
        # self.verticalLayout_3.setStretch(5, 15)
        self.status_monitor.addWidget(self.node3)
        self.horizontalLayout.addLayout(self.status_monitor)

        self.nokia_logo = QtWidgets.QLabel()
        self.nokia_logo.setPixmap(QtGui.QPixmap("../img/bell_logo.png"))
        self.nokia_logo.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.nokia_logo_layout = QtWidgets.QHBoxLayout()
        self.nokia_logo_layout.addStretch(19)
        self.nokia_logo_layout.addWidget(self.nokia_logo)
        self.nokia_logo_layout.addStretch(1)
        self.horizontalLayout.addLayout(self.nokia_logo_layout)

        self._initComBoXs()
        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def _initComBoXs(self):
        self.comboBox_1 = QtWidgets.QComboBox(self.node1)
        self.comboBox_1.setGeometry(440, 7, 90, 30)
        self.comboBox_1.setStyleSheet("border: 0px solid \n"
                                      "rgb(0, 17, 53);\n"
                                      "border-radius: 2px;")
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        # self.verticalLayout.addWidget(self.comboBox_1)
        self.comboBox_1.setCurrentIndex(0)
        self.comboBox_1.currentIndexChanged.connect(self.index_1_changed)
        self.comboBox_1.setFont(QtGui.QFont("Arial", 15))

        self.comboBox_2 = QtWidgets.QComboBox(self.node2)
        self.comboBox_2.setGeometry(440, 7, 90, 30)
        self.comboBox_2.setStyleSheet("border: 0px solid \n"
                                      "rgb(0, 17, 53);\n"
                                      "border-radius: 2px;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        # self.verticalLayout_2.addWidget(self.comboBox_2)
        self.comboBox_2.setCurrentIndex(1)
        self.comboBox_2.currentIndexChanged.connect(self.index_2_changed)
        self.comboBox_2.setFont(QtGui.QFont("Arial", 15))

        self.comboBox_3 = QtWidgets.QComboBox(self.node3)
        self.comboBox_3.setGeometry(440, 7, 90, 30)
        self.comboBox_3.setStyleSheet("border: 0px solid \n"
                                      "rgb(0, 17, 53);\n"
                                      "border-radius: 2px;")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        # self.verticalLayout_3.addWidget(self.comboBox_3)
        self.comboBox_3.setCurrentIndex(2)
        self.comboBox_3.currentIndexChanged.connect(self.index_3_changed)
        self.comboBox_3.setFont(QtGui.QFont("Arial", 15))

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "CFN Resource Perception"))
        self.comboBox_1.setItemText(0, _translate("window", "Node1"))
        self.comboBox_1.setItemText(1, _translate("window", "Node2"))
        self.comboBox_1.setItemText(2, _translate("window", "Node3"))
        self.comboBox_1.setItemText(3, _translate("window", "Node4"))
        self.comboBox_1.setItemText(4, _translate("window", "Node5"))
        self.comboBox_1.setItemText(5, _translate("window", "Node6"))
        self.label_1.setText(_translate("window", "CFN-Node1"))
        self.cpu_1.setText(_translate("window", "CPU"))
        self.cpu_usage_1.setText(_translate("window", "24%"))
        self.mem_1.setText(_translate("window", "MEM"))
        self.mem_usage_1.setText(_translate("window", "24%"))
        self.delay_1.setText(_translate("window", "DELAY"))
        self.delay_num_1.setText(_translate("window", "24ms"))
        self.net_1.setTitle(_translate("window", "NETWORK"))
        self.disk_1.setTitle(_translate("window", "DISK I/O"))
        self.read_label_1.setText(_translate("window", "R/s"))
        self.write_label_1.setText(_translate("window", "W/s"))
        self.sdal_1.setText(_translate("window", "sda1"))
        self.sdal_read_1.setText(_translate("window", "11.9M"))
        self.sdal_write_1.setText(_translate("window", "2.5M"))
        self.sr0_1.setText(_translate("window", "sr0"))
        self.sr0_read_1.setText(_translate("window", "7.9M"))
        self.sr0_write_1.setText(_translate("window", "1.2M"))
        self.file_1.setTitle(_translate("window", "FILE SYS"))
        self.used_label_1.setText(_translate("window", "Used"))
        self.total_label_1.setText(_translate("window", "Total"))
        self.all_1.setText(_translate("window", "/"))
        self.all_used_1.setText(_translate("window", "11.9M"))
        self.all_total_1.setText(_translate("window", "2.5M"))
        self.boot_1.setText(_translate("window", "/boot"))
        self.boot_used_1.setText(_translate("window", "7.9M"))
        self.boot_total_1.setText(_translate("window", "1.2M"))
        self.comboBox_2.setItemText(0, _translate("window", "Node1"))
        self.comboBox_2.setItemText(1, _translate("window", "Node2"))
        self.comboBox_2.setItemText(2, _translate("window", "Node3"))
        self.comboBox_2.setItemText(3, _translate("window", "Node4"))
        self.comboBox_2.setItemText(4, _translate("window", "Node5"))
        self.comboBox_2.setItemText(5, _translate("window", "Node6"))
        self.label_2.setText(_translate("window", "CFN-Node2"))
        self.cpu_2.setText(_translate("window", "CPU"))
        self.cpu_usage_2.setText(_translate("window", "24%"))
        self.mem_2.setText(_translate("window", "MEM"))
        self.mem_usage_2.setText(_translate("window", "24%"))
        self.delay_2.setText(_translate("window", "DELAY"))
        self.delay_num_2.setText(_translate("window", "24ms"))
        self.net_2.setTitle(_translate("window", "NETWORK"))
        self.disk_2.setTitle(_translate("window", "DISK I/O"))
        self.read_label_2.setText(_translate("window", "R/s"))
        self.write_label_2.setText(_translate("window", "W/s"))
        self.sdal_2.setText(_translate("window", "sda1"))
        self.sdal_read_2.setText(_translate("window", "11.9M"))
        self.sdal_write_2.setText(_translate("window", "2.5M"))
        self.sr0_2.setText(_translate("window", "sr0"))
        self.sr0_read_2.setText(_translate("window", "7.9M"))
        self.sr0_write_2.setText(_translate("window", "1.2M"))
        self.file_2.setTitle(_translate("window", "FILE SYS"))
        self.used_label_2.setText(_translate("window", "Used"))
        self.total_label_2.setText(_translate("window", "Total"))
        self.all_2.setText(_translate("window", "/"))
        self.all_used_2.setText(_translate("window", "11.9M"))
        self.all_total_2.setText(_translate("window", "2.5M"))
        self.boot_2.setText(_translate("window", "/boot"))
        self.boot_used_2.setText(_translate("window", "7.9M"))
        self.boot_total_2.setText(_translate("window", "1.2M"))
        self.comboBox_3.setItemText(0, _translate("window", "Node1"))
        self.comboBox_3.setItemText(1, _translate("window", "Node2"))
        self.comboBox_3.setItemText(2, _translate("window", "Node3"))
        self.comboBox_3.setItemText(3, _translate("window", "Node4"))
        self.comboBox_3.setItemText(4, _translate("window", "Node5"))
        self.comboBox_3.setItemText(5, _translate("window", "Node6"))
        self.label_3.setText(_translate("window", "CFN-Node3"))
        self.cpu_3.setText(_translate("window", "CPU"))
        self.cpu_usage_3.setText(_translate("window", "24%"))
        self.mem_3.setText(_translate("window", "MEM"))
        self.mem_usage_3.setText(_translate("window", "24%"))
        self.delay_3.setText(_translate("window", "DELAY"))
        self.delay_num_3.setText(_translate("window", "24ms"))
        self.net_3.setTitle(_translate("window", "NETWORK"))
        self.disk_3.setTitle(_translate("window", "DISK I/O"))
        self.read_label_3.setText(_translate("window", "R/s"))
        self.write_label_3.setText(_translate("window", "W/s"))
        self.sdal_3.setText(_translate("window", "sda1"))
        self.sdal_read_3.setText(_translate("window", "11.9M"))
        self.sdal_write_3.setText(_translate("window", "2.5M"))
        self.sr0_3.setText(_translate("window", "sr0"))
        self.sr0_read_3.setText(_translate("window", "7.9M"))
        self.sr0_write_3.setText(_translate("window", "1.2M"))
        self.file_3.setTitle(_translate("window", "FILE SYS"))
        self.used_label_3.setText(_translate("window", "Used"))
        self.total_label_3.setText(_translate("window", "Total"))
        self.all_3.setText(_translate("window", "/"))
        self.all_used_3.setText(_translate("window", "11.9M"))
        self.all_total_3.setText(_translate("window", "2.5M"))
        self.boot_3.setText(_translate("window", "/boot"))
        self.boot_used_3.setText(_translate("window", "7.9M"))
        self.boot_total_3.setText(_translate("window", "1.2M"))

    def set_data(self, display_node_num, data):
        node_num, cpu, mem, delay, net, s1_r, s1_w, s0_r, s0_w, all_u, all_t, boot_u, boot_t = data

        _translate = QtCore.QCoreApplication.translate

        eval("self.label_" + str(display_node_num) + ".setText(_translate(\"window\", \"CFN-Node" + str(
            node_num) + "\"))")

        eval("self.cpu_usage_" + str(display_node_num) + ".setText(_translate(\"window\", str(cpu) + \"%\"))")
        eval("self.cpu_bar_" + str(display_node_num) + ".setProperty(\"value\", cpu)")
        if cpu <= 50:
            eval("self.cpu_bar_" + str(
                display_node_num) + ".setStyleSheet(\"QProgressBar::chunk {background-color: rgb(\" + str(int(2.55 * "
                                    "cpu * 2)) + \",\" + \"255\" + \",0);}\")")
        else:
            eval("self.cpu_bar_" + str(
                display_node_num) + ".setStyleSheet(\"QProgressBar::chunk {background-color: rgb(\" + \"255\" + \","
                                    "\" + str(int(2.55 * (100 - ((cpu - 50) * 2)))) + \",0);}\")")

        eval("self.mem_usage_" + str(display_node_num) + ".setText(_translate(\"window\", str(mem) + \"%\"))")
        eval("self.mem_bar_" + str(display_node_num) + ".setProperty(\"value\", mem)")

        if mem <= 50:
            eval("self.mem_bar_" + str(
                display_node_num) + ".setStyleSheet(\"QProgressBar::chunk {background-color: rgb(\" + str(int(2.55 * "
                                    "mem * 2)) + \",\" + \"255\" + \",0);}\")")
        else:
            eval("self.mem_bar_" + str(
                display_node_num) + ".setStyleSheet(\"QProgressBar::chunk {background-color: rgb(\" + \"255\" + \","
                                    "\" + str(int(2.55 * (100 - ((mem - 50) * 2)))) + \",0);}\")")

        eval("self.delay_num_" + str(display_node_num) + ".setText(_translate(\"window\", str(delay) + \"ms\"))")
        eval("self.delay_bar_" + str(display_node_num) + ".setProperty(\"value\", delay)")
        if delay <= 50:
            eval("self.delay_bar_" + str(
                display_node_num) + ".setStyleSheet(\"QProgressBar::chunk {background-color: rgb(\" + str(int(2.55 * "
                                    "delay * 2)) + \",\" + \"255\" + \",0);}\")")
        else:
            eval("self.delay_bar_" + str(
                display_node_num) + ".setStyleSheet(\"QProgressBar::chunk {background-color: rgb(\" + \"255\" + \","
                                    "\" + str(int(2.55 * (100 - ((delay - 50) * 2)))) + \",0);}\")")

        eval("self.speed_meter_" + str(display_node_num) + ".setSpeed(net)")

        eval("self.sdal_read_" + str(display_node_num) + ".setText(_translate(\"window\", str(s1_r) + \"M\"))")
        eval("self.sdal_write_" + str(display_node_num) + ".setText(_translate(\"window\", str(s1_w) + \"M\"))")

        eval("self.sr0_read_" + str(display_node_num) + ".setText(_translate(\"window\", str(s0_r) + \"M\"))")
        eval("self.sr0_write_" + str(display_node_num) + ".setText(_translate(\"window\", str(s0_w) + \"M\"))")

        eval("self.all_used_" + str(display_node_num) + ".setText(_translate(\"window\", str(all_u) + \"G\"))")
        eval("self.all_total_" + str(display_node_num) + ".setText(_translate(\"window\", str(all_t) + \"G\"))")

        eval("self.boot_used_" + str(display_node_num) + ".setText(_translate(\"window\", str(boot_u) + \"M\"))")
        eval("self.boot_total_" + str(display_node_num) + ".setText(_translate(\"window\", str(boot_t) + \"M\"))")

    # 这里可以用于实现数据的接收及解析，解析后调用set_data函数更改显示界面
    def update_data(self, display_node_num, node_num):
        data = self.read_json(node_num)
        self.set_data(display_node_num, data)

    # 可以设置一个开始按钮，这个函数作为触发事件，开始调用update_data接收数据并实时显示
    def update_start(self):
        self.timer = QTimer()
        self.timer.timeout.connect(lambda: self.update_data(1, self.comboBox_1.currentIndex() + 1))
        self.timer.timeout.connect(lambda: self.update_data(2, self.comboBox_2.currentIndex() + 1))
        self.timer.timeout.connect(lambda: self.update_data(3, self.comboBox_3.currentIndex() + 1))
        self.timer.start(1000)  # 每秒触发一次

    # 下拉框触发的目标函数，切换展示node，传入node编号
    def index_1_changed(self, index):
        self.switch_master(index + 1)

    def index_2_changed(self, index):
        self.switch_worker1(index + 1)

    def index_3_changed(self, index):
        self.switch_worker2(index + 1)

    # 读取node对应latest json文件，并set data
    def switch_master(self, node_num):
        data = self.read_json(node_num)
        self.set_data(1, data)

    # 读取node对应latest json文件，并set data
    def switch_worker1(self, node_num):
        data = self.read_json(node_num)
        self.set_data(2, data)

    # 读取node对应latest json文件，并set data
    def switch_worker2(self, node_num):
        data = self.read_json(node_num)
        self.set_data(3, data)

    # todo
    # 解析json文件，读取node状态数据，更新cpu和net对应的list
    def read_json(self, node_num):
        cpu = randint(0, 100)
        mem = randint(0, 100)
        delay = randint(0, 100)
        net = randint(0, 100)

        s1_w = randint(0, 100)
        s1_r = randint(0, 100)

        s0_r = randint(0, 100)
        s0_w = randint(0, 100)

        all_u = randint(0, 100)
        all_t = randint(0, 100)

        boot_u = randint(0, 100)
        boot_t = randint(0, 100)

        data = (node_num, cpu, mem, delay, net, s1_r, s1_w, s0_r, s0_w, all_u, all_t, boot_u, boot_t)
        return data


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QWidget()

    ui = Ui_window()
    ui.setupUi(window)

    ui.update_start()

    window.show()
    sys.exit(app.exec_())
